name: Read-daily-data
on:
  push:
    branches: [ "main" ]
jobs:
  read-details:
    name: Read-details
    runs-on: ubuntu-latest
    env:
      DATASTORE_TARGET: ${{ secrets.DATASTORE_TARGET }}
      GITHUB_TOKEN: ${{ secrets.DATASTORE_TOKEN }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Git-setup
        working-directory: ./
        continue-on-error: true
        run: |
          git config --global user.email "bot@<auto>.com"
          git config --global user.name "GithubBot"
      - name: Store-setup
        run: |
          echo $DATASTORE_TARGET
          rm -fr .git
          mkdir data
          cd data
          git init
          TEMP_BRANCH_NAME=dev-$(date +"%Y%m%d-%H%M%S")
          git branch -M $TEMP_BRANCH_NAME
          git remote add origin $DATASTORE_TARGET
          git branch --set-upstream-to=origin/$TEMP_BRANCH_NAME $TEMP_BRANCH_NAME
      - name: Test-commit
        working-directory: ./data
        run: |
          echo "[]" >> touch.json
          git add .
          git commit -m "Auto-fetch gridlist [ci skip]"
          git pull --rebase
          git push