name: Read-daily-data
on:
  push:
    branches: [ "main" ]
jobs:
  read-f1-gridlist:
    name: Read f1 gridlist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Git-setup
        working-directory: ./
        continue-on-error: true
        run: |
          git config --global user.email "bot@<auto>.com"
          git config --global user.name "GithubBot"
      - name: Install-deps
        working-directory: ./
        continue-on-error: true
        run: |
          corepack enable
          pwd
          pnpm install
      - name: Fetch-gridlist
        working-directory: ./
        continue-on-error: true
        run:
          pnpm run fetch:gridlist
      - name: Git-commit-gridlist
        working-directory: ./
        continue-on-error: true
        run: |
          git add .
          git commit -m "Auto-fetch gridlist [ci skip]"
          git pull --rebase
          git push
      - name: Fetch-limit-up
        working-directory: ./
        continue-on-error: true
        run:
          pnpm run fetch:limit-up
      - name: Git-commit-limit-up
        working-directory: ./
        continue-on-error: true
        run: |
          git add .
          git commit -m "Auto-fetch limit-up [ci skip]"
          git pull --rebase
          git push
      - name: Fetch-remaining
        working-directory: ./
        continue-on-error: true
        run:
          pnpm run fetch
      - name: Git-commit-remaining
        working-directory: ./
        run: |
          git add .
          git commit -m "Auto-fetch remaining [ci skip]"
          git pull --rebase
          git push